modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/The-Fireplace-Minecraft-Mods/Unforgiving-Void/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unforgiving-void"
credits="Thanks to BlayTheNinth for making Forgiving Void, which this mod was based off of."
authors="The_Fireplace"

[[mods]]
modId="unforgivingvoid"
version="${file.jarVersion}"
displayName="Unforgiving Void"
description='''
Sends you to the Nether when you fall in the void.
'''

[[dependencies.unforgivingvoid]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.unforgivingvoid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="SERVER"